import React from "react";
import {
    FaRegClock,
    FaUsers,
    FaTrashAlt,
    FaEdit,
    FaListAlt,
    FaTimes,
    FaEye,
    FaCheck,
    FaCopy,
    FaRegSnowflake,
    FaCalendarAlt,
    FaUsersSlash,
    FaMoneyBillAlt,
    FaMoneyBillWaveAlt,
    FaMoneyBillWave,
    FaHamburger,
    FaShoppingCart,
    FaRegMoneyBillAlt,
    FaRegListAlt,
    FaRegChartBar,
    FaTools,
    FaPoll,
    FaWpforms,
    FaPeopleCarry,
    FaNetworkWired,
    FaSignal,
    FaHome,
    FaBorderAll,
    FaBed,
    FaCalculator,
    FaDiagnoses,
    FaCoins,
    FaFingerprint,
    FaGlasses,
    FaCogs,
    FaSignInAlt
} from "react-icons/fa";
const IconComponentArray = {
    FaRegClock,
    FaUsers,
    FaTrashAlt,
    FaEdit,
    FaListAlt,
    FaTimes,
    FaEye,
    FaCheck,
    FaCopy,
    FaRegSnowflake,
    FaCalendarAlt,
    FaUsersSlash,
    FaMoneyBillAlt,
    FaMoneyBillWaveAlt,
    FaMoneyBillWave,
    FaHamburger,
    FaShoppingCart,
    FaRegMoneyBillAlt,
    FaRegListAlt,
    FaRegChartBar,
    FaTools,
    FaPoll,
    FaWpforms,
    FaPeopleCarry,
    FaNetworkWired,
    FaSignal,
    FaHome,
    FaBorderAll,
    FaBed,
    FaDiagnoses,
    FaCalculator,
    FaCoins,
    FaFingerprint,
    FaGlasses,
    FaCogs,
    FaSignInAlt
};

export default ({ name, className }) => {
    const IconComponent = IconComponentArray[name];
    return <IconComponent className={className} />;
};
